all:
	pdflatex H1prelim-19-013.tex && bibtex H1prelim-19-013 && pdflatex H1prelim-19-013.tex && pdflatex H1prelim-19-013.tex 

clean:
	rm -f H1prelim-19-013.aux && rm -f H1prelim-19-013.log && rm -f H1prelim-19-013.out && rm -f H1prelim-19-013.pdf
