all:
	pdflatex H1prelim-19-011.tex && bibtex H1prelim-19-011 && pdflatex H1prelim-19-011.tex && pdflatex H1prelim-19-011.tex 

clean:
	rm -f H1prelim-19-011.aux && rm -f H1prelim-19-011.log && rm -f H1prelim-19-011.out && rm -f H1prelim-19-011.pdf
